---
- hosts: all
  any_errors_fatal: true
  become: true
  tasks:
    - name: include the hardening role
      include_role:
        name: konstruktoid.hardening
      vars:
        block_blacklisted: true
        suid_sgid_permissions: false
        sshd_admin_net:
          - 0.0.0.0/0
        # abra/docker do a lot of ssh'ing in
        # and we can easily reach the hardening role
        # default of 3
        sshd_max_sessions: 400
