---
- hosts: all
  any_errors_fatal: true
  become: true
  tasks:
  - name: Configure swap
    # https://github.com/geerlingguy/ansible-role-swap
    include_role:
      name: geerlingguy.swap
    vars:
      swap_file_size_mb: 2048

  - name: Configure unattended-upgrades
    include_role:
      name: weareinteractive.apt
    vars:
      apt_unattended_upgrades: yes
      apt_unattended_upgrades_automatic_reboot: yes
      apt_unattended_upgrades_automatic_reboot_time: 03:00
      apt_autoremove: yes
      apt_unattended_upgrades_allowed:
      - ${distro_id}:${distro_codename}-security

  - name: Install GnuPG
    package:
      name: 'gnupg'
      state: present

  - name: Docker gpg key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      keyring: /usr/share/keyrings/docker-archive-keyring.gpg
      state: present

  - name: Docker repo
    apt_repository:
      repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ansible_distribution_release}} stable'
      state: present

  - name: Install dependencies
    package:
      name: '{{ item }}'
      state: present
    with_items:
      - apparmor
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-docker

  - name: Ensure docker is running
    ansible.builtin.service:
      name: docker
      enabled: true
      state: started

  - name: Initialize docker swarm
    community.docker.docker_swarm:
      state: present

  - name: Create docker network
    docker_network:
      name: proxy
      driver: overlay

  - name: Allow http(s)
    community.general.ufw:
      rule: allow
      name: WWW Full
      # need this comment or the hardening one will remove it
      comment: ansible managed

  - name: Allow SMTP
    community.general.ufw:
      rule: allow
      direction: out
      port: '587'
      proto: tcp
      # need this comment or the hardening one will remove it
      comment: ansible managed

# docker swarm init
# and had to add "proxy" network, in swarm scope of type overlay
