---
- hosts: all
  any_errors_fatal: true
  become: true
  tasks:
  - name: Docker gpg key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      keyring: /usr/share/keyrings/docker-archive-keyring.gpg
      state: present

  - name: Docker repo
    apt_repository:
      repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bullseye stable'
      state: present

  - name: Install docker
    package:
      name: '{{ item }}'
      state: present
    with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: Allow http(s)
    community.general.ufw:
      rule: allow
      name: WWW Full
      # need this comment or the hardening one will remove it
      comment: ansible managed

# docker swarm init
# and had to add "proxy" network, in swarm scope of type overlay
